### ISSUE TITLE
Change algorithms to take predicate by value

### ISSUE THREAD

**Issue by vinipsmaker** [BoostGSoC14/boost.http#37]
This change will allow predicates with non-const methods like the following one:

```cpp
struct P
{
  bool operator()(boost::string_ref /*v*/)
  {
    ++c;
  }
  unsigned c = 0;
}
```

Also, it's the approach used by `std::*`'s algorithms.

## TODO

- [ ] http://boostgsoc14.github.io/boost.http/reference/header_value_all_of.html
- [ ] http://boostgsoc14.github.io/boost.http/reference/header_value_any_of.html
- [ ] http://boostgsoc14.github.io/boost.http/reference/header_value_none_of.html
